spring:

  server:
    error:
      include-stracktrace: never
      include-message: always

  cloud:
    stream:
      bindings:
        transaction-created-out-0:
          destination: exchange.transaction.events
        warning-limit-out-0:
          destination: exchange.limit.alerts
          binder: rabbit

  application:
    name: transaction_service
  # Configuração do MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/transaction-db


  # Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Configuração do Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Zookeeper geralmente é gerenciado internamente pelo Kafka ou via propriedades específicas
# se você estiver usando um cliente direto, mas para Spring Kafka, o bootstrap-server basta.